#!/bin/bash
# Grab2 script, grab improved:
# Written by: Kyle Walker kwalker@redhat.com


if [ $# -eq 0 ]; then
        echo "ERROR: Please provide a case number!"
elif [ $HOME == "/root" ]; then
	echo "WARNING: Running as root, aborting!"
else
        if [ -d ~/sosreports/ ]; then 
		mkdir ~/sosreports/$1 -p; cd ~/sosreports/$1
	elif [ -d /cases/ ]; then 
		mkdir /cases/$1 -p; cd /cases/$1
	elif [ -d ~/cases/ ]; then 
		mkdir ~/cases/$1 -p; cd ~/cases/$1
	fi

        if command -v getattachments 2>/dev/null; then
		getattachments;
        	setupsos
	else
		echo "ERROR: No getattachments found. Please install getattachments first."
	fi
fi
               
