#!/bin/bash
# Grab2 script, grab improved:
# Written by: Kyle Walker kwalker@redhat.com


if [ $# -eq 0 ]; then
        echo "ERROR: Please provide a case number!"
elif [ $HOME == "/root" ]; then
	echo "WARNING: Running as root, aborting!"
else
        mkdir ~/cases/$1 -p
        cd ~/cases/$1

        getattachments
        setupsos
fi
               
