#!/bin/bash
# Grab2 script, grab improved:
# Written by: Kyle Walker kwalker@redhat.com


if [ $# -eq 0 ]; then
        echo "ERROR: Please provide a case number!"
else
        mkdir ~/sosreports/$1 -p
        cd ~/sosreports/$1

        getattachments
        setupsos
	pwd
fi
               
